version: "3.9"
services:
  web:
    image: "imagename:local"
    build:
      context: .
      args:
        REGISTRY: "containerregistrydev.azurecr.io"
    ports:
      - "8888:80"
    environment:
      - APP_PATH=/html
      - INDEX_HTML=index.dev-wjau.html
