kind: kubebot.values/v1
deployment:
  image: imagename
  livenessProbe: /
  readinessProbe: /
  env:
    - name: ENVIRONMENT
      value: prod
    - name: SITE
      value: wjau
    - name: INDEX_HTML
      value: index.prod-wjau.html
    - name: APP_PATH
      value: /html

configmap:
  path: /html/config/
  files:
    config.js: |
      const WEBAPP_CONFIG = {
        homeUrl: 'https://www.webjet.com.au'
      }

ingress:
  ssi: on
  rewrite-target: /
  rules:
    - hostname: services.webjet.com.au
      path: /web/[product]/[service]